### ISSUE TITLE
Error handling when challenge closes during solving process

### ISSUE THREAD

**Issue by ludwig7685** [xTerradon/hcaptcha-solver#10]
if i copy testing/test.py ( the code copying )
and past it in app.py, run app.py, i get hcaptcha solved!

if i copy the example code in READ.md, i get a error! 

app.py:
![Screenshot (4)](https://github.com/xTerradon/hcaptcha-solver/assets/139857057/e00f75ad-afa8-4929-83f5-a3e1c6aeb485)

main.py:
![Screenshot (5)](https://github.com/xTerradon/hcaptcha-solver/assets/139857057/d2102ad8-2c5c-4348-95dd-40e081b52476)

console:
![Screenshot (6)](https://github.com/xTerradon/hcaptcha-solver/assets/139857057/9fc7f252-aa1b-45d6-a5fb-9ca8b8477e9b)

its REALLY WEIRD!!!!!!!!!! 
I removed the "h" in line 10 last word from "hcaptcha" !!!!!!!! 
And it works!!!!

**Comment by Shaeikh** [comment]
what the heck line 10 is just a comment

in the readme the code is:
```py
from hcaptcha_solver import hcaptcha_solver
from selenium import webdriver

# create Captcha_Solver object to load ML models
captcha_solver = hcaptcha_solver.Captcha_Solver()

# create webdriver and access website with hCaptcha
options = webdriver.ChromeOptions()
options.add_experimental_option('prefs', {'intl.accept_languages': 'en,en_US'}) # set to english
driver = webdriver.Chrome(options=options)
driver.get("https://accounts.hcaptcha.com/demo")

# check for hCaptcha
captcha_solver.is_captcha_present(driver)

# solve hCaptcha
captcha_solver.solve_captcha(driver)
```

**Comment by Shaeikh** [comment]
the error says `Verbose=True` argument is unexpected, removing it works for me

**Comment by xTerradon** [comment]
Hey, thanks for testing the code! Comments do not have an impact on code execution, so the issue lies somewhere different than the "h".
In your case, 'solve_challenge' expects an open challenge view, but recognizes that no open challenge is active. It then throws the Exception explaining the error.
Most likely something was clicked before the code could execute or the captcha timed out. This sometimes happens as the website reloads, things take longer to load than expected etc. It's hard to catch all the possible errors with selenium, but I will try my best to fix it so the program retries solving the captcha instead of aborting

**Comment by Shaeikh** [comment]
For me the `Verbose=True` argument was giving out an error prob becaz of the pkg version but it was fixed after I updated the pkg

code:
```py
from hcaptcha_solver import hcaptcha_solver # hcaptcha_solver-0.2.13
from selenium import webdriver


options = webdriver.ChromeOptions()
driver = webdriver.Chrome(options=options)
captcha_solver = hcaptcha_solver.Captcha_Solver(verbose=True)


options.add_experimental_option('prefs', {'intl.accept_languages': 'en,en_US'})

driver.get("https://accounts.hcaptcha.com/demo")

captcha_solver.is_captcha_present(driver)
captcha_solver.solve_captcha(driver)
```

**Comment by xTerradon** [comment]
@Shaeikh the verbose argument was introduced in v0.2.13  
I am updating the repo quite actively at the moment so make sure to stay up to date. Thanks for your help!

**Comment by xTerradon** [comment]
This issue is adressed in v0.2.14, as the solver restarts the solving process when it encounters an error during the challenge solving steps
