### ISSUE TITLE
👋 Feels good to be the first one trying to use this project

### ISSUE THREAD

**Issue by luxkatana** [xTerradon/hcaptcha-solver#3]
when attempting to do 
```
pip3 install git+https://github.com/xTerradon/hcaptcha-solver/
```
I get an error that says that this is not a python package, explaination? Is this a project or a package?

**Comment by luxkatana** [comment]
```
ERROR: git+https://github.com/xTerradon/hcaptcha-solver does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

**Comment by xTerradon** [comment]
Hey, happy to hear you are interested in this repo. It is an unfinished personal project of mine, not packaged nor maintained. But I actually like the idea of making this a useable package. It currently only supports NNs for a handful of tasks, but the data collection and training could be heavily improved.

What functionality would you like to see? My first thought was an object like `HCaptchaSolver` to which you can pass a selenium webdriver object, with functionality like `is_captcha_present()` and `solve_captcha()`. This is my first time making a package, so I would be happy to hear your ideas.

**Comment by luxkatana** [comment]
> Hey, glad to hear you are interested in this repo. It is an unfinished personal project of mine - not packaged or maintained. But I really like the idea of making it a usable package. It currently only supports NNs for a handful of tasks, but the data collection and training could be greatly improved.
> 
> What features would you like to see? My first thought was an object like HCaptchaSolver to which you can pass a Selenium webdriver object, with functionality like `is_captcha_present()` and `solve_captcha()`. This is my first time creating a package, so I would be happy to hear your ideas.

That sounds great your idea.

**Comment by luxkatana** [comment]
From the [pypi](https://pypi.org/project/hcaptcha-solver/) example that I have seen is that the captcha_handler package is only needed but will it work if I copy only that folder? The Captcha_Handler object needs a ref argument for initialization.

**Comment by xTerradon** [comment]
Hey, the pypi example is currently not working. I picked up the project again and will try to get it up and running in the coming days. At the moment there is no functionality - I will update you in this issues' thread as soon as the first usable package is underway. Thanks for your interest & stay tuned!

**Comment by xTerradon** [comment]
I am happy to announce that the project is now **packaged and ready for alpha testing**! See the installation and usage guide in the [README.md](https://github.com/xTerradon/hcaptcha-solver#readme).

Right now only 7 different tasks can be solved - I will add 3 more models later today. For me this still works to solve captchas in a couple seconds, but I don't know what other tasks hCaptcha will throw at you.
More models are soon to come, currently I am lacking data points to train new models. If you want to contribute (and make the solver better), feel free to check out the `main.ipynb` in `dev`. It has a `collector` where new data can be scraped from hCaptcha, on which I can train new models.

Also, feel free to test the functionalities and give feedback. I will actively maintain this project for the coming weeks and really hope it will be a contribution to the programming community. Cheers!
