### ISSUE TITLE
im the secound guy using this now?

### ISSUE THREAD

**Issue by ludwig7685** [xTerradon/hcaptcha-solver#4]
hi, im as now, the secound guy using it, i looked at the images, and i have no clue why in "cat" are picturs of cars ? 
also, i just want to be on the safe side: 
am i allowed to copy your code and modify it, and might upload it is a "better" version if i get it better? 
if im thinking of it i will ofcorse credit this repo!

**Comment by ludwig7685** [comment]
sorry, with the cats and cars, github had a bug ... now after refreshing the site it shows me the right pictures in the right folders

**Comment by ludwig7685** [comment]
btw! 
how do you get the pictues of cars and all that, you have a bot running to make that or do you manually do it?

**Comment by xTerradon** [comment]
Hey, happy to see another programmer interested! The images in the `./src/v1/` should be sorted correctly, the tags are taken directly from the html that displayed the captcha. The captchas and images are captured automatically using `selenium` , stored as `.png` with reference in a database. The whole process is called in in `main.ipynb` - check that out. 
Feel free to fork my project and use it as you wish. If you find improvements, send me pull requests and I will update the project accordingly. Thanks for the help!

**Comment by xTerradon** [comment]
I am happy to announce that the project is now **packaged and ready for alpha testing**! See the installation and usage guide in the [README.md](https://github.com/xTerradon/hcaptcha-solver#readme).

Regarding scraping: I updated the functionalities of the webscraper located in `dev/collector/`. Check that out if you are interested - if you want you can also contribute by scraping images yourself using the prebuilt tool. It is as easy as clicking a button: the whole scraping and storage process is automated.

Also, feel free to test the functionalities and give feedback. I will actively maintain this project for the coming weeks and really hope it will be a contribution to the programming community. Cheers!
