### ISSUE TITLE
Looking forward to using this.

### ISSUE THREAD

**Issue by GoodOne120** [xTerradon/hcaptcha-solver#5]
Hey, first of all, thanks for working on this project! I believe many developers will find it very useful. I'm also interested in using it, and I'd like to know if there's any ETA for when this package will be released.

Thanks.

**Comment by xTerradon** [comment]
I am happy to announce that the project is now **packaged and ready for alpha testing**! See the installation and usage guide in the [README.md](https://github.com/xTerradon/hcaptcha-solver#readme). 

Right now only 7 different tasks can be solved - I will add 3 more models later today. For me this still works to solve captchas in a couple seconds, but I don't know what other tasks hCaptcha will throw at you.
More models are soon to come, currently I am lacking data points to train new models. If you want to contribute (and make the solver better), feel free to check out the `main.ipynb` in `dev`. It has a `collector` where new data can be scraped from hCaptcha, on which I can train new models.

The project is still in an early development phase and likely not working 100% as intended - so feel free to test the functionalities and give feedback. I will actively maintain this project for the coming weeks and really hope it will be a contribution to the programming community. Cheers!
